minimum_trust_level_to_create_TOC:
  default: 0
  type: enum
  choices:
    - 1
    - 2
    - 3
    - 4
  description:
    en: "The minimum trust level a user must have in order to see the TOC button in the composer"
    zh_CN: "设定可使用 TOC 功能的最低用户等级"
composer_toc_text:
  default: "This topic will contain a table of contents"
  description:
    en: "The instruction document will not be displayed in the text"
    zh_CN: "指示文档，不会在正文显示"
table_of_contents_icon:
  default: "align-left"
anchor_icon:
  default: "hashtag"
test_setting_field: "<a href='#'>seting testing</a>"
